# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: 'zulu' # Alternative distribution options are available.
    - name: Setup Code Coverage
      run: |
        sudo apt-get update && sudo apt-get install glibc-source libxml2 libxrender1 libfontconfig libxext6 libc6 -y
        dotnet tool install --global dotnet-coverage
    - name: SonarCloud Begin
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get Pull Request information, if any
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: | 
        dotnet tool install --global dotnet-sonarscanner
        dotnet sonarscanner begin /k:"studhascja_sqs-psta" /o:"studhascja" /d:sonar.token="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.cs.vscoveragexml.reportsPaths=coverage.xml
    - name: Restore dependencies
      run: dotnet restore sqs/MovieRating.sln
    - name: Build
      run: dotnet build --no-restore sqs/MovieRating.sln
    - name: Test
      env:
        API_KEY: ${{ secrets.API_KEY }}
      run: dotnet test --no-build --verbosity normal sqs/MovieRating.sln
    - name: Coverage
      env:
        API_KEY: ${{ secrets.API_KEY }}
      run: dotnet-coverage collect "dotnet test sqs/MovieRating.sln" -f xml -o "coverage.xml"
    - name: SonarCloud end
      run: dotnet sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get Pull Request information, if any
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}